import { generateCaloriePath } from "@/lib/nutrition/calorie-path";
import { groceryList, type GroceryItem } from "@/lib/nutrition/grocery";
import { dayTarget, planMeals, type MealSlot } from "@/lib/nutrition/meals";
import type { SwapGroup } from "@/components/nutrition/SwapList";

/**
 * Fixtures for the nutrition preview routes.
 *
 * Generated by the real functions, not typed out, so the screens are checked
 * against numbers the engine actually produces. A hand written table would
 * drift from the generator and the drift would show up as a passing test.
 *
 * Long names and awkward totals on purpose: DESIGN.md tell 10 is about the
 * longest real string, not the convenient one.
 */

export const PREVIEW_PATH = generateCaloriePath({
  weekCount: 12,
  startCalories: 2650,
  endCalories: 2200,
  protein: 193,
  deloadWeeks: [4, 8],
  shape: "front_loaded",
});

/** A confirmed and an edited week, so the status column is exercised. */
export const PREVIEW_PATH_MIXED = PREVIEW_PATH.map((row) =>
  row.week === 2
    ? { ...row, status: "confirmed" as const }
    : row.week === 5
      ? { ...row, status: "edited" as const, note: "Held after a bad travel week" }
      : row,
);

export const PREVIEW_CURRENT_WEEK = 5;

const SLOTS: MealSlot[] = [
  { key: "breakfast", name: "Breakfast", share: 0.25 },
  { key: "lunch", name: "Lunch", share: 0.3 },
  { key: "snack", name: "Mid afternoon snack", share: 0.1 },
  { key: "dinner", name: "Dinner and evening", share: 0.35 },
];

const WEEK = PREVIEW_PATH[PREVIEW_CURRENT_WEEK - 1];

export const PREVIEW_TRAINING_TARGET = dayTarget(
  { baseCalories: WEEK.calories, baseProtein: WEEK.protein, perMileCalories: 100 },
  { miles: 7 },
);

export const PREVIEW_REST_TARGET = dayTarget(
  {
    baseCalories: WEEK.calories,
    baseProtein: WEEK.protein,
    perMileCalories: 100,
    restDayCalories: Math.round(WEEK.calories * 0.92),
  },
  { isRest: true },
);

export const PREVIEW_TRAINING_MEALS = planMeals(
  PREVIEW_TRAINING_TARGET.calories,
  PREVIEW_TRAINING_TARGET.protein,
  SLOTS,
);

export const PREVIEW_REST_MEALS = planMeals(
  PREVIEW_REST_TARGET.calories,
  PREVIEW_REST_TARGET.protein,
  SLOTS,
);

const BASKET: GroceryItem[] = [
  { key: "rice", name: "Jasmine rice", unit: "kg", baseQuantity: 2, category: "Carbs" },
  { key: "oats", name: "Rolled oats", unit: "kg", baseQuantity: 1.5, category: "Carbs" },
  { key: "potato", name: "Sweet potato", unit: "kg", baseQuantity: 3, category: "Carbs" },
  { key: "chicken", name: "Chicken breast, skinless", unit: "kg", baseQuantity: 2.5, isProtein: true, category: "Protein" },
  { key: "beef", name: "Lean ground beef, 5 percent", unit: "kg", baseQuantity: 1.2, isProtein: true, category: "Protein" },
  { key: "yoghurt", name: "Greek yoghurt, zero percent", unit: "kg", baseQuantity: 2, isProtein: true, category: "Protein" },
  { key: "oil", name: "Extra virgin olive oil", unit: "ml", baseQuantity: 500, category: "Fats" },
  { key: "nuts", name: "Almonds, unsalted", unit: "g", baseQuantity: 400, category: "Fats" },
  { key: "greens", name: "Mixed leaf salad", unit: "bags", baseQuantity: 4, category: "Vegetables" },
];

export const PREVIEW_GROCERY = groceryList(BASKET, PREVIEW_PATH[0].calories, WEEK.calories);

export const PREVIEW_SWAPS: SwapGroup[] = [
  {
    category: "Carbs",
    swapsFor: "200g cooked jasmine rice",
    options: [
      { key: "potato", name: "Sweet potato, baked", portion: "250g", calories: 215, protein: 4 },
      { key: "pasta", name: "Wholewheat pasta, cooked", portion: "180g", calories: 219, protein: 8 },
      { key: "bagel", name: "Plain bagel", portion: "1 large", calories: 245, protein: 9 },
    ],
  },
  {
    category: "Protein",
    swapsFor: "180g chicken breast",
    options: [
      { key: "cod", name: "Cod fillet", portion: "240g", calories: 197, protein: 43 },
      { key: "turkey", name: "Turkey mince, 5 percent", portion: "175g", calories: 210, protein: 39 },
    ],
  },
];
