/**
 * Every preview screen, named once.
 *
 * The route, the visual suite and the review capture all walk this list. It
 * used to be written out in each of them, which means a screen added to one and
 * not the others is a screen nobody looks at and nothing measures.
 */
export const SCREENS = [
  "roster",
  "roster-stress",
  "roster-dense",
  "roster-empty",
  "queue",
  "queue-empty",
  "builder-exercises",
  "builder-exercises-stress",
  "builder-exercises-empty",
  "program-week",
  "program-week-flagged",
  "program-periodization",
  "nutrition-path",
  "nutrition-path-empty",
  "nutrition-meals",
  "nutrition-meals-rest",
  "nutrition-grocery",
  "nutrition-swaps",
  "nutrition-swaps-empty",
  "intake-goals",
  "intake-medical",
  "intake-medical-errors",
  "intake-running-hidden",
  "builder-questionnaire",
  "builder-questionnaire-empty",
  "blueprint",
  "blueprint-empty",
  "program-draft",
  "program-draft-empty",
  "checkins",
  "checkins-empty",
  "checkin-compare",
  "checkin-thread",
  "checkin-thread-empty",
  "builder-question-bank",
  "checkin-daily-form",
  "checkin-weekly-form",
  "checkin-week1-form",
  "checkin-no-spine-form",
  "queue-lanes",
  "queue-lanes-one",
  "queue-lanes-empty",
  "monday-card",
  "monday-card-quiet",
  "monday-cards",
  "messages",
  "messages-empty",
  "composer",
  "composer-thin",
  "reminders",
  "reminders-sparse",
  "progress",
  "progress-all",
  "progress-thin",
  "progress-empty",
  "progress-table",
  "photos",
  "photos-empty",
  "photos-compare",
  "photos-compare-unavailable",
  "roster-filters",
  "roster-filters-active",
  "roster-bulk",
  "race-build",
  "race-taper",
  "race-week",
  "race-no-goal",
  "race-empty",
  "client-overview",
  "client-overview-new",
] as const;

export type Screen = (typeof SCREENS)[number];
