/**
 * The AI prompt review pack.
 *
 * One file per AI job, each carrying the prompt the portal actually generates
 * against a synthetic client, a response that gets through the parser, and the
 * exact errors the parser gives back for the ways a response goes wrong.
 *
 * Generated rather than written, for the same reason the loop walk is run
 * rather than described: a hand written prompt in a document drifts from the
 * one the portal sends, and the first person to notice is the coach wondering
 * why the output is nothing like the example.
 *
 * tests/unit/ai-prompt-pack.test.ts holds the examples to the parsers, so an
 * example that stops working is a failing test rather than a stale document.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  blueprintDrafterPrompt,
  programDrafterPrompt,
  weeklyReviewPrompt,
} from "../src/lib/ai/prompts";
import { readBlueprintPaste, readProgramPaste } from "../src/lib/ai/paste";
import { PACK_CLIENT, PACK_JOBS } from "../src/lib/ai/pack";

const OUT = path.resolve(__dirname, "../docs/ai-prompts");

function fence(body: string, language = ""): string {
  return ["```" + language, body, "```"].join("\n");
}

/**
 * Runs each bad example through the real parser and prints what came back.
 *
 * Not a list of what the parser is believed to reject. The strings below are
 * whatever it actually said when this file was generated.
 */
function rejections(
  cases: { why: string; paste: string }[],
  parse: (raw: string) => { ok: boolean; error?: string },
): string {
  return cases
    .map((entry) => {
      const result = parse(entry.paste);
      const said = result.ok
        ? "ACCEPTED. This example no longer fails, which means the parser changed."
        : result.error;
      return [`**${entry.why}**`, "", fence(entry.paste, "json"), "", `The portal says: \`${said}\``, ""].join("\n");
    })
    .join("\n");
}

mkdirSync(OUT, { recursive: true });

const written: string[] = [];

for (const job of PACK_JOBS) {
  const prompt =
    job.key === "blueprint-drafter"
      ? blueprintDrafterPrompt(PACK_CLIENT.derived, PACK_CLIENT.answers)
      : job.key === "program-drafter"
        ? programDrafterPrompt(PACK_CLIENT.blueprint, "Twelve week recomposition", 12)
        : weeklyReviewPrompt(PACK_CLIENT.blueprint, PACK_CLIENT.week);

  const parse =
    job.key === "program-drafter"
      ? (raw: string) => readProgramPaste(raw, 12)
      : job.key === "blueprint-drafter"
        ? readBlueprintPaste
        : // The weekly review has no parser yet: the coach reads the changes
          // and accepts them line by line on the card. Said so in the file
          // rather than implied by an empty section.
          null;

  const body = [
    `# ${job.title}`,
    "",
    job.what,
    "",
    "Generated by `npm run ai:pack` against the synthetic client below. Regenerate",
    "it rather than editing it: the point of the file is that the prompt in it is",
    "the one the portal sends.",
    "",
    "---",
    "",
    "## The client it was generated against",
    "",
    PACK_CLIENT.description,
    "",
    "---",
    "",
    "## The prompt",
    "",
    "Paste everything between the fences.",
    "",
    fence(prompt),
    "",
    "---",
    "",
    "## What a good response looks like",
    "",
    job.goodNotes,
    "",
    fence(job.good, "json"),
    "",
    "---",
    "",
    "## What the portal does with it",
    "",
    parse === null
      ? [
          "Nothing parses this one yet. The Monday card is assembled by the portal",
          "from the frozen week, and the drafted changes reach it as `plan_changes`",
          "rows in draft that a coach accepts, edits or rejects one at a time.",
          "",
          "So the thing to judge when reading a response here is whether the three",
          "decision rules were followed, not whether it would parse. In particular:",
          "a single bad week with no flag and no trend should produce no changes at",
          "all, and a response that proposes something anyway is the failure mode to",
          "watch for.",
        ].join("\n")
      : [
          job.parserNotes,
          "",
          "### What it rejects",
          "",
          rejections(job.bad, parse as (raw: string) => { ok: boolean; error?: string }),
        ].join("\n"),
    "",
    "---",
    "",
    "## What it can never change",
    "",
    "Nothing in a paste reaches the derived half of a Blueprint. Goal, duration,",
    "training days, equipment, injury flags and every target are computed from the",
    "intake answers by code, and the paste supplies prose only. A model cannot",
    "change which movements a client with a spinal fusion is allowed to do, whatever",
    "it returns.",
    "",
    "The voice rules are checked and reported as warnings rather than as errors.",
    "The coach approves every word anyway, and refusing a good draft over one dash",
    "would teach them to work around the check.",
    "",
  ].join("\n");

  const file = path.join(OUT, `${job.key}.md`);
  writeFileSync(file, body);
  written.push(file);
}

const readme = [
  "# AI prompt review pack",
  "",
  "One file per AI job. Each carries the prompt the portal generates, a response",
  "that gets through the parser, and the errors the parser gives back when one",
  "does not. Paste a prompt into Claude, read what comes out, and decide whether",
  "the drafting is worth turning on.",
  "",
  "Regenerate with `npm run ai:pack`. Do not edit these by hand: the whole point",
  "is that the prompt in the file is the one the portal sends.",
  "",
  "## The jobs that go through a model",
  "",
  ...PACK_JOBS.map((job) => `- [${job.title}](${job.key}.md) — ${job.what}`),
  "",
  "## The jobs the spec lists that do not",
  "",
  "Part 7 of the spec names seven AI jobs. Four of them are done by code instead,",
  "and each one is deliberate rather than unfinished:",
  "",
  "- **Calorie path proposer.** `generateCaloriePath` computes every week from a",
  "  start point, an end point and the deload weeks, and week twelve equals the",
  "  goal state by construction. A model would produce a plausible curve that does",
  "  not land on the number.",
  "- **Trigger message drafter.** The suggested message is stored on the trigger",
  "  when it is proposed from the client's own numbers, so it is ready before the",
  "  trigger ever fires. Drafting it at 21:00 would put a model call between a",
  "  fired trigger and the queue.",
  "- **Form generator.** The weekly form is built from the spine variable by",
  "  `buildWeeklyForm`, picking the bank questions whose `produces` matches what",
  "  changed last Monday. That is a lookup, not a judgement.",
  "- **Check-in summarizer.** Not built. The Monday card shows the answers with",
  "  the spine question pinned to the top, which is what a coach reads anyway on",
  "  a form of fifteen questions.",
  "",
  "## AI_PROVIDER is off",
  "",
  "Every one of these ships as a copyable prompt plus a paste box. Nothing in the",
  "portal reaches a paid endpoint, and nothing will until `AI_PROVIDER` names a",
  "real provider.",
  "",
].join("\n");

writeFileSync(path.join(OUT, "README.md"), readme);
written.push(path.join(OUT, "README.md"));

process.stdout.write(`\nAI prompt pack\n==============\n\n`);
for (const file of written) {
  process.stdout.write(`  ${path.relative(process.cwd(), file)}\n`);
}
process.stdout.write(`\n${written.length} files.\n`);
