/**
 * The prompts, built server side with the client's real context.
 *
 * Every AI job in the portal ships as a copyable prompt and a paste box, and
 * the real API call sits behind AI_PROVIDER which is off by default. So these
 * are the product, not a fallback: the coach copies one, pastes it wherever
 * they already pay for a model, and pastes the answer back.
 *
 * Every prompt states the output shape and the voice rules. What comes back is
 * checked against both before it is saved, because a rule that only lives in a
 * prompt holds most of the time.
 */

import type { Blueprint, DerivedBlueprint } from "@/lib/blueprint/types";

export const VOICE_RULES = `Voice rules, all of them mandatory:
- Write like a coach texting, not like an assistant.
- Never open with the session name.
- No motivational filler. No "you've got this", no "trust the process".
- Two to five lines for a client message.
- Exactly one real question.
- Use real numbers from the data below, never a vague quantity.
- Match the client's stated tone.
- No dashes used as punctuation anywhere.
- US English.
- Say which session the client has that day when there is one.`;

/** The context block every job receives. Facts only, in a stable order. */
export function contextBlock(derived: DerivedBlueprint): string {
  const lines = [
    `Goal: ${derived.goalType.replace(/_/g, " ")}`,
    `In their words: ${derived.goalStatement || "not stated"}`,
    `Block length: ${derived.durationWeeks} weeks`,
    `Training: ${derived.daysPerWeek} days a week, ${derived.sessionMinutes} minutes, ${derived.preferredDays.join(", ") || "no preferred days"}`,
    `Equipment: ${derived.equipment.join(", ") || "not stated"}`,
    derived.runs
      ? `Running: ${derived.weeklyMileage ?? "unknown"} miles a week, longest ${derived.longestRun ?? "unknown"}${derived.raceDate ? `, race on ${derived.raceDate}` : ""}`
      : "Running: none",
    `Nutrition: ${derived.nutritionStructure || "not stated"}, ${derived.mealsPerDay} meals a day`,
    `Starting weight: ${derived.startWeight ?? "not given"}`,
    `Goal weight: ${derived.goalWeight ?? "none set"}`,
    `Steps on a normal day: ${derived.stepGoal ?? "not given"}`,
    `Sleep: ${derived.sleepHours ?? "not given"} hours`,
    `Injury flags: ${derived.flags.join(", ") || "none"}`,
    `Medical: ${derived.medical.join("; ") || "nothing noted"}`,
    `Constraints: ${derived.constraints.join("; ") || "none"}`,
    `Tone they asked for: ${derived.tone.replace(/_/g, " ")}`,
    `Accountability they asked for, 1 to 10: ${derived.accountability}`,
  ];

  return lines.join("\n");
}

export function blueprintDrafterPrompt(
  derived: DerivedBlueprint,
  rawAnswers: Record<string, unknown>,
): string {
  const freeText = ["goal_statement", "what_worked", "what_failed", "one_thing", "biggest_obstacle", "anything_else", "surgery", "foods_out", "travel"]
    .map((key) => {
      const value = rawAnswers[key];
      return typeof value === "string" && value.trim() ? `${key}: ${value.trim()}` : null;
    })
    .filter(Boolean)
    .join("\n");

  return `You are drafting a coaching blueprint for ELVT. A human coach reads and approves everything you write, so draft, do not decide.

CLIENT FACTS, already extracted. Do not restate them and do not contradict them.
${contextBlock(derived)}

WHAT THEY WROTE THEMSELVES
${freeText || "nothing in free text"}

${VOICE_RULES}

Return exactly this JSON and nothing else:

{
  "summary": "two or three sentences a coach reads before a call. What this person is actually trying to do and what will decide whether it works.",
  "oneThing": "the single behavior this client should be held to. One sentence, specific, observable, something they could do tomorrow.",
  "failureMode": "where this specifically falls apart, in their words where possible, and what the early sign looks like.",
  "toneNotes": "one or two lines on how to write to this person.",
  "triggers": []
}

Leave triggers as an empty array. The portal proposes those from their numbers.`;
}

export function programDrafterPrompt(
  blueprint: Blueprint,
  templateName: string,
  weekCount: number,
): string {
  return `You are writing the rationale for a training block that has already been generated by the ELVT portal. The program itself is built by code from a template and the client's flags, so you are explaining it, not designing it.

CLIENT
${contextBlock(blueprint.derived)}

WHAT THE COACH APPROVED
One thing: ${blueprint.drafted.oneThing}
Failure mode: ${blueprint.drafted.failureMode}
Tone: ${blueprint.drafted.toneNotes}

TEMPLATE APPLIED: ${templateName}, ${weekCount} weeks

${VOICE_RULES}

Return exactly this JSON and nothing else:

{
  "weeks": [
    { "week": 1, "rationale": "one sentence on what this week is for and what has to happen in it" }
  ]
}

One entry per week, ${weekCount} in total. Do not mention exercises by name: substitutions are explained separately by the portal and your version would disagree with it.`;
}

export function weeklyReviewPrompt(
  blueprint: Blueprint,
  context: {
    weekNumber: number;
    score: number;
    focus: string | null;
    adherence: Record<string, number | null>;
    weightChange: number | null;
    checkinAnswers: Record<string, unknown>;
  },
): string {
  return `You are drafting the Monday review for an ELVT client. A human coach accepts, edits or rejects every line, so propose, do not apply.

CLIENT
${contextBlock(blueprint.derived)}
One thing: ${blueprint.drafted.oneThing}
Failure mode: ${blueprint.drafted.failureMode}

WEEK ${context.weekNumber}
Score: ${context.score}
Weakest category: ${context.focus ?? "none below 80"}
Adherence: ${Object.entries(context.adherence).map(([key, value]) => `${key} ${value ?? "not planned"}`).join(", ")}
Weight change on the seven day average: ${context.weightChange ?? "not enough data"}

WHAT THEY SAID
${JSON.stringify(context.checkinAnswers, null, 2)}

THE THREE DECISION RULES. Follow them exactly.
1. A flag at an actionable level is handled the same day, not on Monday.
2. A trend across two weeks is a signal. One bad week is noise.
3. A direct request is always answered, even when the answer is no.
A single bad week with no flag and no trend changes nothing. If that is what
this is, propose no changes and say so.

${VOICE_RULES}

Return exactly this JSON and nothing else:

{
  "changes": [
    { "field": "calories", "from": "2650", "to": "2550", "reason": "one sentence" }
  ],
  "message": "the message to the client, two to five lines, one question, real numbers"
}`;
}
